<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Folder Include="Aggregates\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Dailu.Events\Dailu.Events.csproj" />
    <ProjectReference Include="..\..\..\shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>
</Project>
