// <auto-generated />
using System;
using HabitUser.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HabitUser.Infrastructure.Database.Migrations
{
    [DbContext(typeof(HabitUserDbContext))]
    [Migration("20260927103026_IntegrationSyncLog_Create")]
    partial class IntegrationSyncLog_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("habit_users")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HabitUser.Domain.Entities.HabitUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_habit_users");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_habit_users_created_at_utc");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_habit_users_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.ToTable("habit_users", "habit_users");
                });

            modelBuilder.Entity("HabitUser.Domain.Entities.IntegrationConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("HabitUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_configs");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_integration_configs_created_at_utc");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_integration_configs_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("HabitUserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_configs_habit_user_id_provider")
                        .HasFilter("is_deleted = false");

                    b.ToTable("integration_configs", "habit_users");
                });

            modelBuilder.Entity("HabitUser.Domain.Entities.IntegrationSyncLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivitiesCount")
                        .HasColumnType("integer")
                        .HasColumnName("activities_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("IntegrationConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_config_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SyncedFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_from_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_sync_logs");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_integration_sync_logs_created_at_utc");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_integration_sync_logs_is_deleted")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_integration_sync_logs_started_at_utc");

                    b.HasIndex("IntegrationConfigId", "StartedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_integration_sync_logs_integration_config_id_started_at_utc");

                    b.ToTable("integration_sync_logs", "habit_users");
                });

            modelBuilder.Entity("HabitUser.Domain.Entities.IntegrationConfigEntity", b =>
                {
                    b.HasOne("HabitUser.Domain.Entities.HabitUserEntity", "HabitUser")
                        .WithMany("IntegrationConfigs")
                        .HasForeignKey("HabitUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_configs_habit_users_habit_user_id");

                    b.Navigation("HabitUser");
                });

            modelBuilder.Entity("HabitUser.Domain.Entities.IntegrationSyncLogEntity", b =>
                {
                    b.HasOne("HabitUser.Domain.Entities.IntegrationConfigEntity", "IntegrationConfig")
                        .WithMany()
                        .HasForeignKey("IntegrationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_sync_logs_integration_configs_integration_confi");

                    b.Navigation("IntegrationConfig");
                });

            modelBuilder.Entity("HabitUser.Domain.Entities.HabitUserEntity", b =>
                {
                    b.Navigation("IntegrationConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
