<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\modules\habit\Habit.Infrastructure\Habit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\habit-entry\HabitEntry.Infrastructure\HabitEntry.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\habit-user\HabitUser.Infrastructure\HabitUser.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\tag\Tag.Infrastructure\Tag.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\tag\Tag.Integrations\Tag.Integrations.csproj" />
    <ProjectReference Include="..\..\modules\identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
