name: Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: "10.x"
  NODE_VERSION: "22"

jobs:
  build-backend:
    name: build-backend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    defaults:
      run:
        working-directory: Dailo

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Set up dependency caching
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Dailo.slnx

      - name: Build
        run: dotnet build Dailo.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Dailo.slnx --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish Dailo.slnx --configuration Release --no-restore --no-build

  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    defaults:
      run:
        working-directory: Dailo/Dailo.ClientApp

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: Dailo/Dailo.ClientApp/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          workdir: Dailo/Dailo.ClientApp
          eslint_flags: src
          filter_mode: added
          level: error
          fail_level: error

      - name: Build
        run: npm run build -- --configuration production
