name: Build & Test backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "10.x"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    defaults:
      run:
        working-directory: Dailo

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Set up dependency caching
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Dailo.slnx

      - name: Build
        run: dotnet build Dailo.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Dailo.slnx --configuration Release --no-restore --no-build

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # When pr-mode is set to true, Qodana analyzes only the files that have been changed
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
          upload-result: false

      - name: Publish
        run: dotnet publish Dailo.slnx --configuration Release --no-restore --no-build
